version: '3.8'

services:
  
  app-prod:
    container_name: bots-api-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file: .env.production
    ports:
      - "8080:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    profiles:
      - prod

  db: 
    image: postgres:17-alpine
    container_name: bots-api-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bots-api
    ports:
      - "5432:5432"
    volumes: 
      - db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: bots-api-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-prod
    restart: always    

volumes:
  db-data:
