version: '3.8'

services:
  app-dev:
    container_name: bots-api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env.development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db  
    profiles:
      - dev

  db: 
    image: postgres:17-alpine
    container_name: bots-api-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bots-api
    ports:
      - "5432:5432"
    volumes: 
      - db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: bots-api-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-dev
    restart: always    

volumes:
  db-data:
